D='Lohit Devanagari,velthuis,Gargi,nakula,sahadeva,Sarai'+(S=',Sakal Bharati'),f='feta,'
fam={//by default Noto Sans
 ber:'Tassafout Standard UNICODE,HapaxB APT Niger,Tifinaghe-Ircam Unicode',
 bn:f+'Lohit Bengali,Mukti Narrow,Likhan,Jamrul,Hortuki,Samyak Sans,SolaimanLipi,Rupali'+S,
 gu:'Lohit Gujarati,Padmaa,Rekha,Aakar,Kalapi,Samyak'+S,
 hi:f+'Gargi 1.9,'+D,
 ja:'Sazanami Gothic,Sazanami Mincho,Shinonome Mincho,Kochi Mincho,Mona,VL Gothic,Kochi Gothic,Kozuka Mincho Pro Acro,Kozuka Mincho Pro-VI R',
 jv:'Kemasyuran Jawa,Jawadwipa Adisastra,Awesome Java',
 ka:f+'BPG Serif Modern GPL&GNU',
 km:'Khmer OS System,Khmer OS Siemreap,Khmer OS Content,Khmer OS,Khmer OS Battambang,Khmer OS Freehand',
 kn:'Lohit Kannada,Gubbi,Navilu,Akshar Unicode,Arial Unicode,JanaKannada,Sampige,Tunga,Mallige,Kedage'+S,
 ko:'NanumGothicCoding,UnBatang,Baekmuk Batang,UnDotum,Baekmuk Gulim',
 lo:'Phetsarath OT,Saysettha OT',
 ml:f+'Lohit Malayalam,Rachana_04,Meera_04,Meera,Rachana,AnjaliOldlipi,Chilanka,RaghuMalayalam,Dyuthi,Suruma,Kalyani'+S,
 mr:'Lohit Marathi',
 my:'Padauk,Padauk-book',
 ne:f+D+',Lohit Nepali',
 pa:f+'Lohit Punjabi,singh,AnmolUni,Saab,AnmolUni,Raavi'+S,
 si:'LKLUG',
 ta:f+'Lohit Tamil,Samyak Tamil,TAMu_Maduram,TAMu_Kadampari,TAMu_Kalyani'+S,
 te:f+'Lohit Telugu,Pothana2000,Vemana2000,Srujana,Ramaneeya Fon,Ponnala,RaviPrakash,LakkiReddy'+S,
 th:'ArundinaSansMono,Garuda,Kinnari,Loma,Norasi',
 zh:'WenQuanYi,WenQuanYi Zen Hei,AR PL UMing,AR PL UKai,Uming'}